apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
data:
  MB_ADMIN_EMAIL: {{ .Values.secrets.MB_ADMIN_EMAIL | b64enc | quote }}
  MB_ADMIN_FIRST_NAME: {{ .Values.secrets.MB_ADMIN_FIRST_NAME | b64enc | quote }}
  MB_ADMIN_PASSWORD: {{ .Values.secrets.MB_ADMIN_PASSWORD | b64enc | quote }}
  MB_DB_USER: {{ .Values.secrets.MB_DB_USER | b64enc | quote }}
  MB_DB_PASS: {{ .Values.secrets.MB_DB_PASS | b64enc | quote }}
  MB_DB_HOST: {{ .Values.secrets.MB_DB_HOST | b64enc | quote }}
  OPENMRS_DB_HOST: {{ .Values.secrets.OPENMRS_DB_HOST | b64enc | quote }}
  OPENMRS_DB_USERNAME: {{ .Values.secrets.OPENMRS_DB_USERNAME | b64enc | quote }}
  OPENMRS_DB_PASSWORD: {{ .Values.secrets.OPENMRS_DB_PASSWORD | b64enc | quote }}
  MART_DB_HOST: {{ .Values.secrets.MART_DB_HOST | b64enc | quote }}
  MART_DB_USERNAME: {{ .Values.secrets.MART_DB_USERNAME | b64enc | quote }}
  MART_DB_PASSWORD: {{ .Values.secrets.MART_DB_PASSWORD | b64enc | quote }}

 